mintel/dex-k8s-authenticator

charts/dex/templates/_helpers.tpl, charts/dex/templates/deployment.yaml, charts/dex/templates/rbac.yaml, charts/dex/templates/serviceaccount.yaml, charts/dex/values.yaml
Using best-practise here as per:
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md
- Generate service-account name using a template
- Fix RoleBinding namespace
- Generate rbac rules based on rbac.create (not serviceAccount.create)
=> Fixes for rbac and serviceAccountName generation

Dockerfile, README.md, charts/dex-k8s-authenticator/templates/ca_secrets.yaml, charts/dex-k8s-authenticator/templates/deployment.yaml, charts/dex-k8s-authenticator/values.yaml, entrypoint.sh
Use entrypoint.sh to update CA certificates store at runtime rather than docker container buildtime
=> Add support for self-signed certificates at container runtime 

charts/dex-k8s-authenticator/templates/ingress.yaml, charts/dex/templates/ingress.yaml
Ingress can't setup routing currently.
nginx-ingress-controller has log as follow.
```
W0309 18:15:25.105640       7 controller.go:739] service system/dex-k8s-authenticator does not have any active endpoints
```
Service port set to ingress was the cause, and i fixed it.
=> Fix service port to bind to ingress in helm chart

templates/kubeconfig.html
Useful when you want to define another kubecfg.
`export KUBECONFIG=/path/kubecfg`
=> Explicitly define the CA certificate path

main.go, templates.go, templates/kubeconfig.html
Hi guy,
K8S CA certificate is contained into the cluster and/or stored on nodes filesystem. It is quite tricky to expose an endpoint over http/https to serve the certificate, and it requires a lot of conf. And for example, if I hold it into kube-system namespace near its pk, I do not want to use an http(s) endpoint to serve it thinking I could increase the attack surface.
So I propose to be able to bind the certificate into the config as a string.
```
clusters:
- name: k8s-cluster
short_description: "K8S Cluster"
description: "This is where you generate token to access the cluster..."
client_secret: ZXhhbXBsZS1hcHAtc2VjcmV0
issuer:  https://toto:32000
k8s_master_uri: https://10.30.12.100:6443
client_id: example-app
redirect_uri: http://127.0.0.1:5555/callback
k8s_ca_pem: |
-----BEGIN …
```
=> Support pem file as k8s cert

Dockerfile
The multistage build was currently copying all the source code and
the intermediate dependencies and artifacts to the final docker image.
This lead to a final size of about 120MB.
Only copying the final binary and static content slims down the image
to about 20MB of size.
=> Slim down final docker container size

Dockerfile, entrypoint.sh, main.go
Make possible to provide extra trusted root ca (as many you want/need).
It can be useful if your distant dex is presenting a certificate signed with an internal rootca, you will not have any alert on tls negociation between dex-k8s-authenticator and dex...
Example:
```
clusters:
- name: k8s-cluster
short_description: "K8S Cluster"
description: "This is where you generate token to access the cluster..."
client_secret: ZXhhbXBsZS1hcHAtc2VjcmV0
issuer:  https://toto:32000
k8s_master_uri: https://10.30.12.100:6443
client_id: example-app
redirect_uri: http://127.0.0.1:5555/callback
listen: http://0.0.0.0:5555
debug: false
trusted_root_ca:
- |
-----BEGIN CERTIFICATE-----
MIIGJDCCBAygAwIBAgIJAPp7Aw5evQcOMA0GCSqGSIb3DQEBCwUAMIGeMQswCQYD
VQQGEwJGUjEOMAwGA1UECAwFUGFyaXMxDjAMBgNVBAcMBVBhcmlzMQ4wDAYDV …
```
=> Provide extra rootca

charts/dex-k8s-authenticator/templates/configmap.yaml
The `dex-k8s-authenticator` Go binary has support for passing an IDentity Provider CA cert URL to the [template render for `linux-mac-common.html`](https://github.com/mintel/dex-k8s-authenticator/blob/master/templates/linux-mac-common.html#L2-L13).  However, the Helm chart was missing this parameter so it was impossible to pass through to the `ConfigMap` containing `config.yaml` for the `Pod`.
This PR fixes the issue by adding parameter `idpCaURI` that conditionally passes through to `idp_ca_uri` in `ConfigMap`.  Tested against `kops` Kubernetes cluster, [Vault PKI backend](https://www.vaultproject.io/docs/secrets/pki/index.html) with Root from `kops` cluster + Intermediate CA chain and [`ca_chain` URI](https://www.vaultproject.io/api/secret/pki/index.html#read-ca-certificate-chain), the …
=> Fix missing idp_ca_uri parameter in dex-k8s-authenticator ConfigMap

charts/dex/templates/deployment.yaml, charts/dex/templates/secret.yaml, charts/dex/values.yaml
PR adds TLS support for Dex when using self-signed certs (for use with Helm).
The Helm values are updated to provide:
- `tls.create` to enable the creation of the secrets
- `tls.certificate` for the certificate
- `tls.key` for the private key
The TLS example options are now available in the Helm values (but commented out).
- SSL cert/key installed into `/etc/dex/tls/`
- Port fixed to `5556` (probably ok?)
- Can only configure one of https or http (probably ok?)
- Health probes configured to use https scheme if `tls.create` set
=> Adding tls options for dex via Helm chart

charts/dex-k8s-authenticator/templates/_helpers.tpl, charts/dex-k8s-authenticator/templates/deployment.yaml, charts/dex/templates/_helpers.tpl, charts/dex/templates/deployment.yaml
Should resolve #56 
We also introduce an optional `healthCheckPath` helm setting to fully customize this.
If not specified, attempt to set path from `ingress.path`, and also, in the case of `dex-k8s-authenticator`, also the `web_path_prefix`
=> Added option for custom readiness/liveness probe path

charts/dex-k8s-authenticator/templates/deployment.yaml, charts/dex/templates/deployment.yaml
When we run helm commands pods are not picking new config immediately, we have to restart/delete pods so that they pick new config on the restart.
=> pods will pick configmap changes immediately

examples/config.yaml, main.go, templates.go, templates/linux-mac-common.html, templates/windows-tab.html
This PR adds an optional cluster config `static_context_name: true` which avoids the usage of the username for the context in templates like `{{ .Username }}-{{ .ClusterName }}`
We do need this option to unify the context name on workstations.
=> Add option to avoid usage of username for kube context

charts/dex-k8s-authenticator/templates/configmap.yaml
idp ca field in the helm chart is useless as is. If you specify it with a multiline ca pem file, the chart won't install complaining about configmap.yaml validation issue. This PR fixes it.
=> Fix idp ca field in the helm chart

charts/dex-k8s-authenticator/values.yaml
Do not use latest, as it may break existing releases in the future.
=> Helm chart: pin docker tag: 1.1.0

dex-auth.go, docs/config.md, main.go
This is very useful if SSL assets for dex-k8s-authenticator are cread with [cert-manager](https://docs.cert-manager.io/en/latest/reference/certificates.html#certificate-duration-and-renewal-window) or a similar tool that will create a secret dynamically
=> Support loading IDP_CA_PEM and TRUSTED_ROOT_CA from file

templates/id-token-tab.html, templates/kubeconfig.html
@fciocchetti does this look alright?
If the wording makes sense, I'll update the screenshot in the main readme and we can merge it in.
I would like to add some blurb about how the token could be used by other services too, but nothing too specific.
*note, it's a fake token ;)
=> Added tab to display only the id-token

templates/linux-mac-common.html
ClientSecret can contain special char (such as ``#``), then break the copy/paste.
=> Quote CLI options values to protect copy/paste

Dockerfile
If the process receiving the signal is PID 1, it gets special treatment
by the kernel; if it hasn't registered a handler for the signal, the
kernel won't fall back to default behavior, and nothing happens. Prior
to this patch, the entrypoint script is PID 1 in the container, and by
default, shell does not register SIGTERM handler. As a result, `docker
stop` will not work properly when trying to gracefully shutdown the
container.
This patch adds `tini` to be the PID 1 in the container to do PID 1
things, and correctly propagate the SIGTERM signal.
=> Propagate SIGTERM for graceful shutdown

charts/dex/templates/deployment.yaml
currently indentation is off
```diff
+       affinity:
+       nodeAffinity:
+         requiredDuringSchedulingIgnoredDuringExecution:
+           nodeSelectorTerms:
```
that leads to
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Deployment.spec.template.spec): unknown field "nodeAffinity" in io.k8s.api.core.v1.PodSpec
```
=> Fix dex affinity indentation

.circleci/config.yml, charts/dex/out.yaml
Was using upstream `latest` of helm, which of course now is now helm v3.
Various options are no longer available - we'll bump to v3 oneday, but right now stick with v2 in CI.
=> Pin helm to 2.x (for now) and kubeval in CI

examples/config.yaml, main.go, templates.go, templates/linux-mac-common.html
This PR adds support for setting a default namespace which is included in the `set-context` part of the instructions.
=> Add namespace field to cluster config

dex-auth.go, docs/config.md, main.go
We wanted to use this with AWS Cognito, but the default scopes aren't compatible with Cognito User Pool OIDC settings (without a custom resource server). 
With configurable scopes, we were able to use Cognito as an OIDC provider in place of Dex. 
I know that technically this tool is designed for Dex...but this removes that restriction to a particular idP while preserving existing functionality.
=> Allow specifying OIDC scopes per cluster

README.md
This changes `README.md` to reflect the new Github URI for the dex project.
=> README: dex moved

charts/dex-k8s-authenticator/templates/deployment.yaml
for nodeSelector & tolerations fields
=> fix: bad indentation in deployment template

dex-auth.go, docs/config.md, main.go
My use-case is:
- dex with two connectors, e.g. github with id "id1" and Microsoft with id "id2"
- two dex-k8s-authenticator apps:
- /login/app1 -> this should call dex with github connector
- /login/app2 -> this should call dex with microsoft connector
The goal is to skip dex login page where you need to choose your connector.
With this change, I can configure my separate dex-k8s-authenticator apps with `connector_id: id1` and `connector_id: i2` respectively for cluster context. Then visiting a separate authenticator app will point me directly to a specified connector
=> Pass optional connector_id to cluster_context

charts/dex-k8s-authenticator/templates/service.yaml
This PR add a possibility to insert custom labels in dex-k8s-authenticator service. At my work we need to include some custom labels to create the service correctly. Do you think this would be usefull for the project?
=> allow custom labels in dex-k8s-authenticator service

Dockerfile, main.go
- Removing insecure ciphers, pure RSA is not forward-secret
- Curve preference for elliptic curves
- Upgrade go.mod file to go1.16
- Upgrade builder image to golang:1.16-alpine3.13
- Base image upgrade to alpine:3.13
- resolves #160
Signed-off-by: Anton Ouzounov <aouzounov@vmware.com>
=> feat(tls): reorder TLS ciphersuites and curve preference

charts/dex-k8s-authenticator/templates/deployment.yaml, charts/dex-k8s-authenticator/values.yaml
dex-k8s-authenticator allows usage of env variables in configuration: https://github.com/mintel/dex-k8s-authenticator/blob/98a3d45cb878f0baad9b3e19019fcbf6f9d42584/docs/config.md#environment-variable-support
but there seems to be no way to pass environment variables into the pod.
this pr allows passing data from secret as environment variables same way dex chart does it:
- https://github.com/dexidp/helm-charts/blob/8d69f098b027da77ea3f0507c7ab923a23adf6c0/charts/dex/values.yaml#L64
- https://github.com/dexidp/helm-charts/blob/8d69f098b027da77ea3f0507c7ab923a23adf6c0/charts/dex/templates/deployment.yaml#L65
=> Allow configuration using env in helm chart
